### ISSUE TITLE
Doesnt Work?

### ISSUE THREAD

**Issue by St47b0und** [Tacogamerman/ByeBlocker#9]
asks for url, proceeds to do nothing. I added https://www.

**Comment by Jimbothelimbo** [comment]
Net lift is unblocked but this site is just white screen and when it loads it’s blocked is the any way to do through play code console or something I’m new to the is stuff

**Comment by unblocker343** [comment]
idk how to use it

**Comment by vitcostarx** [comment]
Pretty sure this is glitched.

**Comment by Tacogamerman** [comment]
guys I'm not gonna fix it 💀

**Comment by v1ndictiv33** [comment]
taco gamer i need this unblocked man D:
i want to play games at school :(

**Comment by Anonymus616** [comment]
> Pretty sure this is glitched.

I'm pretty sure it can, we just need told how to. I got it working in OneCompiler.com but when prompting you to type in a url, you do so, but it doesn't do anything afterwards

**Comment by Anonymus616** [comment]
> guys I'm not gonna fix it 💀

I legit just need this for discord.
Also, if this doesn't work, and you guys are at your wits end and would do anything, use this:
https://docs.google.com/document/d/1ebE4sCBR6u7B4xPfSPKt29IpgOpdv8L7oe-DRHiu9GE/edit 
It's an online vpn built-in browser, which is guaranteed unblocked, because the links refresh every 24 hours, but there's a catch... The links that are guaranteed unblocked, you have to pay a subscription for. But, like I said, If you're willing to do ANYTHING, here ya go.

**Comment by v1ndictiv33** [comment]
i got it to work, i just had to enter the link in an HTML code runner,
enter the code, put in disablesecurly.com, and it worked. Its blocked now
sadly

**Comment by Tacogamerman** [comment]
i made like other stuff that works better than this
go on my profile
